using System;
using System.Collections.Generic;

namespace DesertRainSoap.Data
{
    public static class SAPValues
    {
        public static readonly Dictionary<string, double> Values = new Dictionary<string, double> (StringComparer.OrdinalIgnoreCase)
        {
            {"Almond Butter", 0.134},
            {"Almond Oil", 0.139},
            {"Aloe Butter",	0.171},
            {"Apricot Kernel Oil", 0.135},
            {"Argan Oil", 0.135},
            {"Avocado Butter", 0.133},
            {"Avocado Oil", 0.133},
            {"Beeswax", 0.067},
            {"Borage Oil", 0.135},
            {"Canola Oil", 0.133},
            {"Castor Oil", 0.128}, 
            {"Cocoa Butter", 0.138}, 
            {"Coconut Oil", 0.183},
            {"Coconut Oil, Fractionated", 0.232},
            {"Coffee Bean Oil, Roasted", 0.128},
            {"Corn Oil", 0.137},
            {"Cottonseed Oil", 0.138},
            {"Cranberry Seed Oil", 0.135},
            {"Cucumber Seed Oil", 0.133},
            {"Cupuacu Butter", 0.137},
            {"Emu Oil", 0.135},
            {"Evening Primrose Oil", 0.135},
            {"Flax Oil", 0.135},
            {"Ghee", 0.162},
            {"Goose Fat", 0.137},
            {"Grapeseed Oil", 0.137},
            {"Hazelnut Oil", 0.139},
            {"Hemp Oil", 0.138},
            {"Illipe Butter", 0.137},
            {"Jojoba Oil", 0.066},
            {"Karanja Oil", 0.132},
            {"Kokum Butter", 0.135},
            {"Kpangnan Butter", 0.135},
            {"Kukui Nut Oil", 0.135},
            {"Lanolin", 0.076},
            {"Lard", 0.141},
            {"Laurel Fruit Oil", 0.141},
            {"Lauric Acid", 0.200},
            {"Linseed Oil", 0.135},
            {"Loofa Seed Oil", 0.133},
            {"Macadamia Nut Butter", 0.134},
            {"Macadamia Nut Oil", 0.139},
            {"Mango Seed Butter", 0.136},
            {"Mango Seed Oil", 0.135},
            {"Marula Oil", 0.137},
            {"Meadowfoam Oil", 0.120},
            {"Milk", 0.162},
            {"Mink Oil", 0.140},
            {"Moringa Oil", 0.182},
            {"Mowrah Butter", 0.137},
            {"Murumuru Butter", 0.138},
            {"Mustard Oil", 0.123},
            {"Myristic Acid", 0.200},
            {"Neem Tree Oil", 0.138},
            {"Oat Oil", 0.135},
            {"Oleic Acid", 0.144},
            {"Olive Oil", 0.135},
            {"Olive Oil Pomace", 0.134},
            {"Palm Kernel Oil", 0.178},
            {"Palm Kernel Oil Flakes", 0.178},
            {"Palm Oil", 0.142},
            {"Papaya Seed Oil", 0.113},
            {"Passion Fruit Seed Oil", 0.130},
            {"Peach Kernel Oil", 0.135},
            {"Peanut Oil", 0.137},
            {"Pistachio Oil", 0.133},
            {"Plum Kernel Oil", 0.135},
            {"Pomegranate Seed Oil", 0.135},
            {"Poppy Seed Oil", 0.138},
            {"Pumpkin Seed Oil (Virgin)", 0.139},
            {"Rabbit Fat", 0.143},
            {"Rapeseed Oil", 0.125},
            {"Red Palm Butter", 0.142},
            {"Rice Bran Oil", 0.133},
            {"Rosehip Oil", 0.133},
            {"Safflower Oil", 0.137},
            {"Safflower Oil (High Oleic)", 0.137},
            {"Sal Butter", 0.132},
            {"Saw Palmetto Extract", 0.164},
            {"Saw Palmetto Oil", 0.157},
            {"Sea Buckthorn Oil (Seed)", 0.139},
            {"Sea Buckthorn Oil (Seed and Berry)", 0.139},
            {"Sesame Oil", 0.134},
            {"Shea Butter", 0.128},
            {"Shea Oil", 0.132},
            {"Soybean Oil", 0.136},
            {"Soybean (27.5% Hydrogenated)", 0.137},
            {"Stearic Acid", 0.153},
            {"Sunflower Oil", 0.135},
            {"Sunflower Oil (High Oleic)", 0.135},
            {"Tallow", 0.143},
            {"Tucuma Seed Butter", 0.170},
            {"Walnut Oil", 0.135},
            {"Wheat Germ Oil", 0.130},
        };
    }
}

//Naniniwala ko kayo!! kaya ka!!